services:
  app:
    build: ./backend
    container_name: pomo_app
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=pomo_admin
      - DB_PASSWORD=pomo123
      - DB_DATABASE=pomodb

  postgres:
    image: postgres:15
    container_name: pomo_postgres
    restart: always
    environment:
      POSTGRES_USER: pomo_admin
      POSTGRES_PASSWORD: pomo123
      POSTGRES_DB: pomodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: pomo_redis
    ports:
      - "6379:6379"

  adminer:
    image: adminer:latest
    container_name: pomo_adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres


volumes:
  postgres_data:
